### ISSUE TITLE
Performance based on fixed polar only?

### ISSUE THREAD

**Issue by mvannas** [joabakk/signalk-polar#25]
As far as I read your code right, the sqlite3 database is updated all the time and performance deltas are generated based on previously stored values? 

I find this useful if you are trying to improve your polar data, but for racing purposes I would like to have an option to always show data based on fixed (non-updating) polar information. Making a separate plugin for this function would probably be trivial, but I with few changes and a option in settings your plugin could also (AFAIK) support this sort of function? Aka. make an option that would disable updating of the polar? I think the engine parameter already might do this, If I read the code right, then updates to the polar table are not made, but targets are still being calculated into the performance.* signalk paths? 

Also possible that I somehow missed a functionality in the code and it works differently from previously presumed?

**Comment by joabakk** [comment]
Hi @mvannas. You are right that the plugin compares performance and updates the polar table if the engine is off or that check is disabled. What you are looking for may be found in https://github.com/SignalK/polars-plugin. Please note that there is/was a discussion on the approach in https://github.com/SignalK/specification/pull/360. Since this plugin is somewhat of a resource hog, it may be an option to do a batch run on historical data  when not sailing and then use that as a polar table for future trips. This was an early approach. When the comparisons are not made but the plugin is active, the paths are still populated from the db.

I'm happy to hear your proposals. My current thinking is that any graphing ui or server could use static or dynamic data from any source, so pending the outcome of the specification PR discussion, I will try to align this plugin with the spec to be.

**Comment by mvannas** [comment]
True, tkurkis polars-plugin has what I was really looking for. I noticed the PR360 before but somehow assumed that the other plugin they were talking about was the now deprecated polar-performance by SBender and missed this plugin. 

Nevertheless, I see a really useful function that might be an "extension" to your plugin is to collect the performance data dynamically, but instead of using it for performance.* path values to use it to create information about previous tack performances, aka. longer term performance (performance.* paths are meant for current performance). In order to improve performance it might be very useful to have some output on slightly longer term (like previous tack or tacks, or for based on last 1,5,10 minutes?) performance information. 

To achieve this, you're software could either store data as it is, or use the performance information provided by tkurki polars-plugin and store this also?

**Comment by joabakk** [comment]
And this brings us to https://github.com/SignalK/specification/issues/89. Agreed this can be done by a local hack in a plugin, but I would prefer to have a method ironed out in the spec to cover this. I also think that plugins should not compete for server routes to the resources group, so there may be an issue with competing routes to the same server path.

**Comment by joabakk** [comment]
Closing this now.
